"use strict";

//EXPRESIÓN REGULAR QUE BUSCA TEXTO ALFABÉTICO
const expReg_abc = /[a-zA-ÿ\u00f1\u00d1çÇ]+/g; //LOS CORCHETES SIRVEN PARA QUE CUALQUIER CARACTER QUE COINCIDA CON LOS NOMBRADOS EN LA EXPREG SEA CAPTURADO
//DE LO CONTRARIO SOLO DEVOLVERÍA EL VALOR QUE COINCIDA CON EL EXACTO DE LA REGEXP
//LA G HACE QUE LA BUSQUEDA SEA GLOBAL

//const expReg_abc = /Manolo/g       SOLO SI COINCIDE CON MANOLO

//QUIERO BUSCAR LAS COINCIDENCIAS DE UNA CADENA
var textoAbc = "zVuDa".match(expReg_abc);
textoAbc = textoAbc.join("")
console.log(textoAbc);
alert(textoAbc);
